services:
    proxyserver:
        image: kimykstar/learndocker
        ports:
            - '3000:3000'
        depends_on:
            - mysql
            - registry
    mysql:
        image: mysql
        restart: always
        environment:
            MYSQL_DATABASE: test
            MYSQL_USER: user
            MYSQL_PASSWORD: rladudrhks
            MYSQL_ROOT_PASSWORD: password
        ports:
            - '3306:3306'
    registry:
        image: kimykstar/localregistry
        privileged: true
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
