services:
    proxyserver:
        image: kimykstar/learndocker
        ports:
            - '3000:3000'
        depends_on:
            - mysql
    mysql:
        image: mysql
        restart: always
        environment:
            MYSQL_DATABASE: test
            MYSQL_USER: user
            MYSQL_PASSWORD: rladudrhks
            MYSQL_ROOT_PASSWORD: password
        ports:
            - '3306:3306'
